ALTER TABLE users
    ADD COLUMN IF NOT EXISTS provider     VARCHAR(10) NOT NULL DEFAULT 'LOCAL',
    ADD COLUMN IF NOT EXISTS provider_id  VARCHAR(100);

ALTER TABLE users ALTER COLUMN password DROP NOT NULL;
