ALTER TABLE spaces ADD COLUMN open_time TIME NOT NULL DEFAULT '09:00';
ALTER TABLE spaces ADD COLUMN close_time TIME NOT NULL DEFAULT '21:00';
ALTER TABLE spaces ADD COLUMN slot_minutes INT NOT NULL DEFAULT 60;
