ALTER TABLE spaces ADD COLUMN IF NOT EXISTS open_time TIME NOT NULL DEFAULT '09:00';
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS close_time TIME NOT NULL DEFAULT '21:00';
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS slot_minutes INT NOT NULL DEFAULT 60;
