spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        prepareThreshold: 0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      ssl:
        enabled: true

logging:
  level:
    com.churchhub: WARN
